name: example
description: Example
version: 0.0.1
#homepage: https://www.example.com
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  firebase_admin_interop: 
    path: ../
  node_interop: ^0.0.4

dev_dependencies:
  test: ^0.12.24

transformers:
  - $dart2js
  - node_interop
