language: dart

dart:
- dev

before_install:
- nvm install node
- node --version

before_script:
- npm install

dart_task:
- test: --reporter expanded -j 1
- dartfmt
- dartanalyzer: --fatal-warnings lib
- ./tool/ddc_test.sh
