name: firebase_admin_interop
description: Interop for Firebase Admin Node SDK
version: 0.0.1
homepage: https://github.com/pulyaevskiy/firebase-admin-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  node_interop: ^0.0.4
  meta: ^1.0.5

dev_dependencies:
  test: ^0.12.24
