name: firebase_admin_interop
description: Interop for Firebase Admin Node SDK
version: 0.0.1
#homepage: https://www.example.com
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
 node_interop: ^0.0.4

dev_dependencies:
  test: ^0.12.24

transformers:
  - $dart2js:
      $include: "example/firebase_admin_interop_example.dart" 
  - node_interop:
      include: "**/*.dart.js"
