name: firebase_admin_interop
description: Interop for Firebase Admin Node.js SDK
version: 1.0.0-dev.11.0
homepage: https://github.com/pulyaevskiy/firebase-admin-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  js: ^0.6.1
  node_interop: ^1.0.0-dev.6.0
  meta: ^1.0.5
  quiver_hashcode: "^1.0.0"

dev_dependencies:
  test: ^0.12.24
  build_runner: ^0.7.9
  build_node_compilers: ^0.1.0
