name: firebase_admin_interop
description: Interop for Firebase Admin Node SDK
version: 1.0.0-dev.1.0
homepage: https://github.com/pulyaevskiy/firebase-admin-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev.19.0 <2.0.0'

dependencies:
  func: ^1.0.0
  js: ^0.6.1
  node_interop:
    git:
      url: https://github.com/pulyaevskiy/node-interop.git
      ref: dart20
  meta: ^1.0.5
  quiver_hashcode: "^1.0.0"

dev_dependencies:
  test: ^0.12.24
  build_runner: ^0.7.8
  build_web_compilers:
    git:
      url: https://github.com/pulyaevskiy/build.git
      path: build_web_compilers
      ref: node-support
